### PR TITLE
Create March 6 challenge

### PR DESCRIPTION
**Pull request by pathawks**
This is not ready to merge yet, but I thought I'd create a stub for the March 6 coding challenge.

Need to actually decide on a challenge and fill in the appropriate info before merging.

Any ideas for a challenge?

### CODE REVIEW

**Comment by ChadH1971** [comment]
Let's do something practical. Temperature conversion.

**Comment by pathawks** [comment]
Yes, that should not take too long.

For bonus points, we could let the user type something like "80F" or "20C" and then automatically convert it to the other system. Too much?

**Comment by ChadH1971** [comment]
Yeah, that's good.

**Comment by pathawks** [comment]
Something along the lines of:
- Prompt the user to `Enter a temperature in either Celsius(c) or Fahrenheit(f):`
- Get both the temperature and system from StdIn. Keep in mind that temperature is not necessarily measured in integers.
- Convert the temperature from the system that the user entered to the other system, and output a message along the lines of `59.0°F == 15°C`
  Only show one decimal place.

### Formulas
- **°C** = (**°F** − 32) × 5/9  
- **°F** = **°C** × 9/5 + 32  

### Sample

``` text
Enter a temperature in either Celsius(c) or Fahrenheit(f): 59f
59.0°F == 15.0°C
```

:grey_question:

**Comment by ChadH1971** [comment]
Yeah, that looks good. Additional challenge could be to take the user entry
of 80F just as it is and separate it for processing.

**Comment by pathawks** [comment]
> Additional challenge could be to take the user entry of 80F just as it is and separate it for processing.

That's what I was going for. Input would be `80F`**`<enter>`**

You could get it with `in.nextDouble(); in.next();`

How can I make that more clear?

**Comment by ChadH1971** [comment]
Maybe just by limiting to a single prompt:
"Enter the temperature and scale (eg. 80F): "

**Comment by pathawks** [comment]
Yeah, that sounds good.

On a tangent, our assignments for class usually have very tight design specifications; an assignment is (I'm sure) easier to grade if you can expect the output to conform to a very specific form.

For the club, since the assignments aren't graded, perhaps we could be a bit more free with the specifications (ie. Come up with your own prompts). Maybe one of our members has some really cleaver User Experience ideas that had not occurred to us.

The downside is that it might encourage Blinking Cursor Syndrome, if you're not given a firm starting point.

Probably we keep this one rather strict and see how things play out at the next meeting. Just something to think about.

**Comment by pathawks** [comment]
Here is what I am looking at:
https://github.com/AICSC/Coding-Challenges/blob/March6/2015/03-06/Challenge.md

**Comment by ChadH1971** [comment]
Agreed, I have mixed feelings about a strict guideline. On one hand I want
to foster creativity. On the other, I want to foster the practice of design
protocols and project leader...

**Comment by ChadH1971** [comment]
Sooooo, all we have to do is reveal the url? I'd like to do a hands on with
posting pull requests from the last challenge.

**Comment by pathawks** [comment]
> Sooooo, all we have to do is reveal the url?

Here's the cool part: All we need to do is click the green **Merge pull request** button and all the changes will go live in the _master_ branch. This includes adding a link to this challenge to the [front page of the repo](https://github.com/AICSC/Coding-Challenges).

Would you like to do the honors?

At the next meeting, we should all do a step-by-step _Creating a Pull Request_ together and get everybody's code from the first challenge posted.

**Comment by pathawks** [comment]
Yay! :+1:

**Pull request merged**
