### PR TITLE
Create codeWithMe.md

### PR DESCRIPTION
**Pull request by ChadH1971**
Creating a new folder for October 2016 Code With Me

### CODE REVIEW

**Comment by pathawks** [comment]
What happened here?

**Comment by ChadH1971** [comment]
Learning process, trying to understand gitbash and properly locating directory structure.

**Comment by pathawks** [comment]
Where did the file go? I don't understand.

**Comment by ChadH1971** [comment]
It's okay. It wasn't something I wanted to keep. I probably made some mistakes but everything is fine. Nothing from previous folders has been damaged. I made changes to the Readme.md to to update from Artificial [sic] Intellegence to Bakersfield College, that's the only change I wanted to keep. We are planning try using github more with new members and getting back into sharing code exercises. We might want to make the master here a protected branch as well.

**Comment by pathawks** [comment]
`master` _is_ a protected branch

**Pull request merged**
